module Utils.CursorShapes where

import Foreign.C

cursorDefault = 1
cursorDefault :: CUInt
cursorContextMenu = 2
cursorContextMenu :: CUInt
cursorHelp = 3
cursorHelp :: CUInt
cursorPointer = 4
cursorPointer :: CUInt
cursorProgress = 5
cursorProgress :: CUInt
cursorWait = 6
cursorWait :: CUInt
cursorCell = 7
cursorCell :: CUInt
cursorCrosshair = 8
cursorCrosshair :: CUInt
cursorText = 9
cursorText :: CUInt
cursorVerticalText = 10
cursorVerticalText :: CUInt
cursorAlias = 11
cursorAlias :: CUInt
cursorCopy = 12
cursorCopy :: CUInt
cursorMove = 13
cursorMove :: CUInt
cursorNoDrop = 14
cursorNoDrop :: CUInt
cursorNotAllowed = 15
cursorNotAllowed :: CUInt
cursorGrab = 16
cursorGrab :: CUInt
cursorGrabbing = 17
cursorGrabbing :: CUInt
cursorEResize = 18
cursorEResize :: CUInt
cursorNResize = 19
cursorNResize :: CUInt
cursorNeResize = 20
cursorNeResize :: CUInt
cursorNwResize = 21
cursorNwResize :: CUInt
cursorSResize = 22
cursorSResize :: CUInt
cursorSeResize = 23
cursorSeResize :: CUInt
cursorSwResize = 24
cursorSwResize :: CUInt
cursorWResize = 25
cursorWResize :: CUInt
cursorEwResize = 26
cursorEwResize :: CUInt
cursorNsResize = 27
cursorNsResize :: CUInt
cursorNeswResize = 28
cursorNeswResize :: CUInt
cursorNwseResize = 29
cursorNwseResize :: CUInt
cursorColResize = 30
cursorColResize :: CUInt
cursorRowResize = 31
cursorRowResize :: CUInt
cursorAllScroll = 32
cursorAllScroll :: CUInt
cursorZoomIn = 33
cursorZoomIn :: CUInt
cursorZoomOut = 34
cursorZoomOut :: CUInt
cursorDndAsksince = 35
cursorDndAsksince :: CUInt
cursorAllResizesince = 36
cursorAllResizesince :: CUInt
